[package]
name = "explore-table-postgres"
version = "0.1.0"
authors = ["Einar Lielmanis <einars@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.15.2"
clap = "2.33.0"
